### ISSUE TITLE
decipher telegram messages from chartink and generate buy/sell signals

### ISSUE THREAD

**Issue by pannet1** [pannet1/halo-hash#12]
1) client needs some guidance to send telegram messages from chartink 
2) after which generate buy/sell signals from telegram messages

**Comment by MaheswaranPalaniselvan** [comment]
ok

**Comment by MaheswaranPalaniselvan** [comment]
Client has subscribed to IFFT for telegram updates from Chartink. Awating telegram messages to proceed making the changes
