### ISSUE TITLE
index or value error when short_listed.csv

### ISSUE THREAD

**Issue by pannet1** [pannet1/halo-hash#3]
when short_listed.csv is entered manually there is a value or out of index error. the same screenshot was attached in the halo hash several times now. suspicion is ..we are getting this issue if there is
 
-  an extra space or line break 
-  there is already a stock in the previous line.

**Comment by MaheswaranPalaniselvan** [comment]
Not reproduce-able..

**Comment by pannet1** [comment]
did not get the issue again.
